// One integrated "AI verification command center": a Machine Read scan whose
// results light up an entity graph and resolve into a recommendation verdict.
// Server component — all text is in the DOM; only entrances/glow are CSS.

const rows = [
  ['Identity', 'Verified'],
  ['Organization', 'Detected'],
  ['Provider entity', 'Connected'],
  ['Services', 'Mapped'],
  ['Locations', 'Verified'],
  ['Reviews', 'Matched'],
  ['Profiles', 'Aligned'],
  ['FAQ / schema', 'Present'],
  ['Agent action path', 'Clear'],
];

// Entity graph nodes positioned around a central Organization node.
const C = { x: 184, y: 160 };
const nodes = [
  { id: 'person', label: 'Person', x: 184, y: 46 },
  { id: 'service', label: 'Service', x: 286, y: 92 },
  { id: 'place', label: 'Place', x: 320, y: 178 },
  { id: 'review', label: 'Review', x: 286, y: 262 },
  { id: 'website', label: 'Website', x: 184, y: 290 },
  { id: 'faq', label: 'FAQ', x: 82, y: 262 },
  { id: 'profile', label: 'Profile', x: 48, y: 178 },
  { id: 'offer', label: 'Offer', x: 82, y: 92 },
];

export default function HeroVerificationSystem() {
  return (
    <div
      className="relative w-full overflow-hidden soft-glow"
      style={{
        background: 'linear-gradient(160deg, var(--d-bg-3), var(--d-bg-2) 70%)',
        border: '1px solid var(--d-line-s)',
        borderRadius: '20px',
        padding: '20px 22px 22px',
      }}
    >
      <div className="mr-scanline" />

      {/* Header */}
      <div className="flex items-center justify-between mb-5">
        <div className="flex items-center gap-2 min-w-0">
          <span className="node-pulse" style={{ width: 8, height: 8, borderRadius: 99, background: 'var(--d-ok)', flexShrink: 0 }} />
          <span className="font-mono text-xs truncate" style={{ color: 'var(--d-fg-dim)', letterSpacing: '0.03em' }}>
            Scanning: <span style={{ color: 'var(--d-fg)' }}>examplebusiness.com</span>
          </span>
        </div>
        <span className="font-mono text-[10px]" style={{ color: 'var(--d-accent)', letterSpacing: '0.18em' }}>MACHINE READ</span>
      </div>

      {/* Scan + graph */}
      <div className="grid grid-cols-1 md:grid-cols-[1fr_minmax(0,300px)] gap-5 items-center mb-5">
        {/* Scan rows with dotted leaders */}
        <div className="flex flex-col gap-2">
          {rows.map(([label, status], i) => (
            <div
              key={label}
              className="mr-row flex items-baseline gap-2"
              style={{ animationDelay: `${0.2 + i * 0.1}s` }}
            >
              <span className="font-mono text-xs" style={{ color: 'var(--d-fg-dim)', whiteSpace: 'nowrap' }}>{label}</span>
              <span className="flex-1" style={{ borderBottom: '1px dotted var(--d-line-s)', transform: 'translateY(-3px)' }} />
              <span className="font-mono text-xs flex items-center gap-1" style={{ color: 'var(--d-ok)', whiteSpace: 'nowrap' }}>
                <span style={{ fontSize: 10 }}>✓</span>{status}
              </span>
            </div>
          ))}
        </div>

        {/* Entity graph — generated by the scan */}
        <div className="hidden md:block">
          <svg viewBox="0 0 368 336" width="100%" role="img" aria-label="Entity graph: an Organization connected to Person, Service, Place, Review, Website, FAQ, Profile, and Offer">
            {/* edges */}
            {nodes.map((n, i) => (
              <line
                key={`e-${n.id}`}
                x1={C.x} y1={C.y} x2={n.x} y2={n.y}
                className="svg-edge"
                stroke="var(--d-accent)" strokeWidth="1" strokeOpacity="0.5"
                strokeDasharray="200" style={{ animationDelay: `${0.3 + i * 0.12}s` }}
              />
            ))}
            {/* outer nodes */}
            {nodes.map((n, i) => (
              <g key={`n-${n.id}`} className="svg-node node-pulse" style={{ animationDelay: `${0.5 + i * 0.12}s` }}>
                <circle cx={n.x} cy={n.y} r="20" fill="var(--d-bg-3)" stroke="var(--d-line-s)" strokeWidth="1" />
                <circle cx={n.x} cy={n.y} r="4" fill="var(--d-accent)" />
                <text x={n.x} y={n.y + 33} textAnchor="middle" className="font-mono" fontSize="9" fill="var(--d-fg-dim)" letterSpacing="0.5">{n.label}</text>
              </g>
            ))}
            {/* center: Organization */}
            <g>
              <circle cx={C.x} cy={C.y} r="30" fill="var(--d-accent)" fillOpacity="0.12" stroke="var(--d-accent)" strokeWidth="1.5" />
              <circle cx={C.x} cy={C.y} r="7" fill="var(--d-accent)" className="node-pulse" />
              <text x={C.x} y={C.y + 48} textAnchor="middle" className="font-mono" fontSize="9.5" fill="var(--d-accent)" letterSpacing="0.5">Organization</text>
            </g>
          </svg>
        </div>
      </div>

      {/* Recommendation verdict */}
      <div style={{ background: 'rgba(122,240,194,0.06)', border: '1px solid rgba(122,240,194,0.3)', borderRadius: '14px', padding: '16px 18px' }}>
        <div className="flex items-center justify-between mb-2">
          <span className="font-inter text-sm" style={{ color: 'var(--d-fg-dim)' }}>AI Recommendation Confidence</span>
          <span className="font-mono text-[11px]" style={{ color: 'var(--d-ok)', letterSpacing: '0.1em', background: 'rgba(122,240,194,0.12)', borderRadius: 99, padding: '4px 12px' }}>HIGH</span>
        </div>
        <div style={{ height: 6, borderRadius: 99, background: 'var(--d-bg)', overflow: 'hidden', marginBottom: '12px' }}>
          <div className="mr-bar-fill" style={{ height: '100%', width: '92%', borderRadius: 99, background: 'linear-gradient(90deg, var(--d-accent-2), var(--d-ok))' }} />
        </div>
        <p className="font-inter text-xs" style={{ color: 'var(--d-fg-mute)', lineHeight: 1.5 }}>
          <span style={{ color: 'var(--d-ok)', fontWeight: 600 }}>Safe to recommend.</span>{' '}
          Entity verified across website, schema, services, locations, reviews, and trusted profiles.
        </p>
      </div>
    </div>
  );
}
