import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Below The Content Layer — Where Your Real SEO, AEO & GEO Opportunity Lives | KodeCite.ai',
  description:
    'The content layer conversation is everywhere right now — and most of it stops too soon. Here is the layer underneath that determines whether AI recommends you or skips you entirely.',
  alternates: { canonical: 'https://www.kodecite.ai/blog/below-the-content-layer' },
  openGraph: {
    title: 'Below The Content Layer — Where Your Real SEO, AEO & GEO Opportunity Lives',
    description:
      'The content layer conversation is everywhere right now — and most of it stops too soon. Here is the layer underneath that determines whether AI recommends you or skips you entirely.',
    url: 'https://www.kodecite.ai/blog/below-the-content-layer',
    type: 'article',
    publishedTime: '2026-04-22',
    authors: ['Mark Abplanalp'],
  },
};

const blogPostingSchema = {
  '@context': 'https://schema.org',
  '@type': 'BlogPosting',
  headline: 'Below The Content Layer — Where Your Real SEO, AEO & GEO Opportunity Lives',
  description:
    'The content layer conversation is everywhere right now — and most of it stops too soon. Here is the layer underneath that determines whether AI recommends you or skips you entirely.',
  author: { '@id': 'https://www.kodecite.ai/#founder' },
  publisher: { '@id': 'https://www.kodecite.ai/#organization' },
  datePublished: '2026-04-22',
  dateModified: '2026-04-22',
  mainEntityOfPage: { '@type': 'WebPage', '@id': 'https://www.kodecite.ai/blog/below-the-content-layer' },
  url: 'https://www.kodecite.ai/blog/below-the-content-layer',
  keywords: ['entity graph', 'content layer', 'SEO', 'AEO', 'GEO', 'schema markup', 'AI search visibility', 'answer engine optimization', 'generative engine optimization'],
  articleSection: 'AEO & AI Search',
  wordCount: 2400,
  about: [
    { '@type': 'Thing', name: 'Entity Graph' },
    { '@type': 'Thing', name: 'Content Layer' },
    { '@type': 'Thing', name: 'Answer Engine Optimization' },
    { '@type': 'Thing', name: 'Schema Markup' },
  ],
  mentions: [
    { '@type': 'Thing', name: 'Schema.org' },
    { '@type': 'Thing', name: 'ChatGPT' },
    { '@type': 'Thing', name: 'Perplexity' },
    { '@type': 'Thing', name: 'Google AI Overviews' },
    { '@type': 'Thing', name: 'Rank Math' },
    { '@type': 'Thing', name: 'Yoast' },
  ],
};

const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  '@id': 'https://www.kodecite.ai/blog/below-the-content-layer#faq',
  mainEntity: [
    {
      '@type': 'Question',
      name: "What is the content layer in SEO and why isn't it enough for AI search?",
      acceptedAnswer: {
        '@type': 'Answer',
        text: "The content layer refers to everything visible on your pages — structured answers, FAQ sections, heading hierarchy, semantic depth, and topical authority. It's necessary and AI search systems do reward it. But it only solves half the problem. AI systems don't just read your content — they verify the identity behind it. Without a correctly built entity graph underneath your content, AI can find your pages but can't confirm who's behind them — which means it won't recommend your business with confidence.",
      },
    },
    {
      '@type': 'Question',
      name: 'What is an entity graph and how does it differ from regular schema?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'An entity graph is Schema.org deployed correctly — every element of a business connected through stable identity anchors into a single machine-readable identity. Regular schema, typically generated by plugins, produces disconnected blocks that the machine reads as fragments. An entity graph connects every entity across every page into a coherent, traversable identity network.',
      },
    },
    {
      '@type': 'Question',
      name: 'Why do plugins like Rank Math and Yoast fail to create a proper entity graph?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: "Plugins are a useful starting point but they generate disconnected blocks rather than a connected identity network. They produce generic markup that drifts over time as updates break things, themes conflict, and duplicate signals accumulate. Schema hygiene — keeping the entity graph consistent, conflict-free, and current — requires ongoing engineering discipline that plugins weren't designed to provide.",
      },
    },
    {
      '@type': 'Question',
      name: 'Why is proper schema implementation considered software engineering rather than SEO or marketing?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: "Building a coherent entity graph requires custom JSON-LD written in code, stable identity anchors managed across every page, nested object relationships validated against a formal spec, and server-side delivery that AI crawlers can parse on a cold load. These are development tasks — not marketing tasks. Schema was classified as technical SEO which put it in the hands of practitioners who implemented it as a checkbox rather than an engineering deliverable. That mismatch is why most schema implementations fail.",
      },
    },
    {
      '@type': 'Question',
      name: 'How do I know if my entity graph is working correctly?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: "Paste your site's schema into an LLM and ask it what it can verify about your business. If it can clearly identify who runs the business, what services you offer, where you operate, what credentials you hold, and how long you've been doing it — your entity graph is working. If it returns gaps, contradictions, or generic information — your schema is producing noise rather than signal.",
      },
    },
  ],
};

const breadcrumbSchema = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://www.kodecite.ai' },
    { '@type': 'ListItem', position: 2, name: 'Blog', item: 'https://www.kodecite.ai/blog' },
    { '@type': 'ListItem', position: 3, name: 'Below The Content Layer', item: 'https://www.kodecite.ai/blog/below-the-content-layer' },
  ],
};

export default function BelowTheContentLayer() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(blogPostingSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />

      {/* Hero */}
      <section className="pt-36 pb-16 bg-[#f8f5f0] px-4 relative overflow-hidden">
        <div className="absolute inset-0 hero-grid-bg opacity-40 pointer-events-none" />
        <div className="max-w-4xl mx-auto relative z-10">
          <nav className="flex items-center gap-2 text-sm font-poppins text-[#6a5a48] mb-8">
            <Link href="/" className="hover:text-[#a0723a] transition-colors">Home</Link>
            <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" /></svg>
            <Link href="/blog" className="hover:text-[#a0723a] transition-colors">Blog</Link>
            <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" /></svg>
            <span className="text-[#0a0806] truncate">Below The Content Layer</span>
          </nav>

          <div className="flex items-center gap-3 mb-6">
            <span className="category-tag">AEO &amp; AI Search</span>
            <span className="text-[#6a5a48] text-sm font-poppins">10 min read</span>
          </div>

          <h1 className="font-playfair font-bold text-4xl md:text-5xl lg:text-6xl text-[#0a0806] mb-6 leading-tight">
            Below The Content Layer —{' '}
            <span className="text-[#a0723a]">Where Your Real SEO, AEO &amp; GEO Opportunity Lives</span>
          </h1>

          <p className="text-[#6a5a48] text-xl font-poppins leading-relaxed max-w-3xl">
            The content layer conversation is everywhere right now — and most of it stops too soon. Here is the layer underneath that determines whether AI recommends you or skips you entirely.
          </p>

          <div className="flex items-center gap-6 mt-8 pt-8 border-t border-[rgba(100,70,30,0.2)]">
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-full bg-[#a0723a] flex items-center justify-center">
                <span className="text-[#f8f5f0] font-bold text-sm font-poppins">MA</span>
              </div>
              <div>
                <p className="text-[#0a0806] text-sm font-semibold font-poppins">Mark Abplanalp</p>
                <p className="text-[#6a5a48] text-xs font-poppins">April 22, 2026</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      <div className="section-divider" />

      {/* Body + Sidebar — placeholder */}
      <section className="py-16 bg-[#f8f5f0] px-4">
        <div className="max-w-6xl mx-auto">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-12">

            <article className="lg:col-span-2">
              <div className="prose-content font-poppins">
                <p className="text-[#6a5a48] text-lg leading-relaxed mb-6">
                  Article body coming in next prompt.
                </p>
              </div>
            </article>

            <aside className="lg:col-span-1">
              <div className="sticky top-28 space-y-6">
                <div className="bg-[#f2ede4] rounded-xl border border-[rgba(160,114,58,0.3)] p-6">
                  <p className="font-poppins font-bold text-[#0a0806] text-lg mb-3 leading-snug">Find Out If AI Can Read You</p>
                  <p className="text-[#6a5a48] text-sm font-poppins leading-relaxed mb-5">
                    We audit your entity graph and show you exactly what AI systems can and can&apos;t verify about your business right now.
                  </p>
                  <Link href="/contact" className="btn-gold w-full text-center text-sm font-bold py-3 rounded-md block">Get Your Free AEO Audit</Link>
                </div>
              </div>
            </aside>

          </div>
        </div>
      </section>

      <div className="section-divider" />

      {/* CTA */}
      <section className="py-20 bg-[#1c1814] px-4">
        <div className="max-w-3xl mx-auto text-center">
          <p className="eyebrow mb-4">THE CONTENT LAYER IS NECESSARY — IT&apos;S JUST NOT SUFFICIENT</p>
          <h2 className="font-poppins font-bold text-3xl md:text-4xl text-[rgba(240,232,216,0.9)] mb-4">
            Below the Content Layer Is Where Your Real Opportunity Lives
          </h2>
          <p className="text-[rgba(240,232,216,0.6)] font-poppins mb-8 leading-relaxed">
            Most of your competitors haven&apos;t looked there yet. Start with a{' '}
            <Link href="/contact" className="text-[#a0723a] hover:underline">free AEO Audit</Link>{' '}
            and find out exactly what AI can and can&apos;t verify about your business right now.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link href="/contact" className="btn-gold text-base font-bold px-8 py-4 rounded-md inline-block">Get Your Free AEO Audit</Link>
            <Link href="/blog" className="btn-gold-outline text-base font-bold px-8 py-4 rounded-md inline-block">Read More Articles</Link>
          </div>
        </div>
      </section>
    </>
  );
}
